trigger:
  branches:
    include:
      - main # This pipeline runs when you push to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  # --- ‼️ CHANGE THESE THREE VALUES ‼️ ---
  acrLoginServer: 'meshappregistry.azurecr.io'   # The "Login server" from your ACR in the Azure Portal
  acrServiceConnection: 'acr-connection'            # The service connection name you created
  imageName: 'mesh-monolithic-app'                  # The name for your application's image

  # --- You don't need to change these ---
  imageTag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build and Push to ACR'
    steps:
    - task: Docker@2
      displayName: 'Build and Push'
      inputs:
        command: 'buildAndPush'
        # This points to the Dockerfile in your repository's root
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: $(acrServiceConnection)
        repository: $(imageName)
        tags: |
          $(imageTag)
          latest